// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalPortal.Order.Data;

namespace RentalPortal.Order.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20190410123356_InitialOrderDbMigration")]
    partial class InitialOrderDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentalPortal.Order.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("EquipmentId");

                    b.Property<int>("NoOfDays");

                    b.Property<string>("UserId");

                    b.HasKey("CartItemId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("EquipmentType");

                    b.Property<string>("Name");

                    b.Property<int>("StockCount");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.OrderRequest", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Email");

                    b.Property<int>("OrderStatus");

                    b.HasKey("OrderId");

                    b.ToTable("OrderRequests");
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.OrderRequestItem", b =>
                {
                    b.Property<int>("OrderRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("EquipmentId");

                    b.Property<int>("OrderId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("OrderRequestItemId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRequestItem");
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("SettingId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.CartItem", b =>
                {
                    b.HasOne("RentalPortal.Order.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RentalPortal.Order.Entities.OrderRequestItem", b =>
                {
                    b.HasOne("RentalPortal.Order.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RentalPortal.Order.Entities.OrderRequest", "OrderRequest")
                        .WithMany("OrderRequestItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
